# Generated by Django 4.0.3 on 2022-04-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0002_alter_menubutton_url_alter_menusubbutton_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menubutton',
            name='url',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='menusubbutton',
            name='url',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
