# Generated by Django 4.0.3 on 2022-04-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0003_alter_menubutton_url_alter_menusubbutton_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatgamepasswd',
            name='app',
        ),
        migrations.AddField(
            model_name='exploregame',
            name='passwd_init',
            field=models.TextField(default='0', max_length=5, verbose_name='本游戏密码的开头字符'),
        ),
        migrations.AddField(
            model_name='wechatgamepasswd',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wxcloudrun.exploregame'),
        ),
    ]
