# Generated by Django 4.0.3 on 2022-04-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0004_remove_wechatgamepasswd_app_exploregame_passwd_init_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exploregame',
            name='passwd_init',
        ),
    ]
