# Generated by Django 4.0.3 on 2022-04-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0005_remove_exploregame_passwd_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploregame',
            name='passwd_init',
            field=models.TextField(default='0', max_length=5, verbose_name='本游戏密码的开头字符'),
        ),
    ]
