# Generated by Django 4.0.3 on 2022-04-16 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0007_alter_exploregame_passwd_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatgamepasswd',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wxcloudrun.wechatapp'),
        ),
    ]
