# Generated by Django 4.0.3 on 2022-04-17 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0008_wechatgamepasswd_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatgamepasswd',
            name='app',
        ),
    ]
