# Generated by Django 4.0.3 on 2022-04-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0009_remove_wechatgamepasswd_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploregamequest',
            name='back_quest',
            field=models.CharField(default='', max_length=100, verbose_name='返回到某个任务的名称，留空表示返回到开始'),
        ),
        migrations.AddField(
            model_name='exploregamequest',
            name='comment_when_available',
            field=models.CharField(default='可选择', max_length=100, verbose_name='满足挑战条件时显示的提示'),
        ),
        migrations.AddField(
            model_name='exploregamequest',
            name='comment_when_unavailable',
            field=models.CharField(default='还不能选择', max_length=100, verbose_name='未满足挑战条件时显示的提示'),
        ),
        migrations.AddField(
            model_name='exploregamequest',
            name='next_list',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='下一步任务分支选项，以｜分隔，只有在这个列表中的任务才来作为下一步'),
        ),
        migrations.AddField(
            model_name='exploregamequest',
            name='show_if_unavailable',
            field=models.BooleanField(default=False, verbose_name='未满足挑战条件时是否显示'),
        ),
        migrations.AddField(
            model_name='exploregamequest',
            name='show_next',
            field=models.BooleanField(default=True, verbose_name='是否显示下一步分支选项，如果不显示，则作为问答题来跳转下一步'),
        ),
    ]
