# Generated by Django 4.0.3 on 2022-04-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0010_exploregamequest_back_quest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploregamequest',
            name='comment_when_clear',
            field=models.CharField(default='已完成', max_length=100, verbose_name='已完成任务时显示的提示'),
        ),
    ]
