# Generated by Django 4.0.3 on 2022-04-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0011_exploregamequest_comment_when_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploregame',
            name='entry',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='游戏入口任务，留空表示直接显示所有可以挑战任务'),
        ),
    ]
