# Generated by Django 4.0.3 on 2022-04-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0012_exploregame_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploregame',
            name='passwd_init',
            field=models.CharField(blank=True, default='0', max_length=5, verbose_name='本游戏密码的开头字符'),
        ),
        migrations.AlterField(
            model_name='exploregame',
            name='settings_file',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='exploregamequest',
            name='answer_list',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='谜底列表，以｜分隔'),
        ),
        migrations.AlterField(
            model_name='exploregamequest',
            name='back_quest',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='返回到某个任务的名称，留空表示返回到开始'),
        ),
        migrations.AlterField(
            model_name='exploregamequest',
            name='question_data',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='谜面'),
        ),
        migrations.AlterField(
            model_name='exploregamequest',
            name='reward',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='本题奖励内容'),
        ),
        migrations.AlterField(
            model_name='exploregamequest',
            name='show_next',
            field=models.BooleanField(default=True, verbose_name='是否显示下一步分支选项，如果不显示，则以answer_list的答案来跳转下一步'),
        ),
    ]
