# Generated by Django 4.0.3 on 2022-04-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0013_alter_exploregame_passwd_init_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploregamequest',
            name='audio_link',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='音频文件链接'),
        ),
    ]
