# Generated by Django 4.0.3 on 2022-04-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0014_exploregamequest_audio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploregame',
            name='settings_file',
            field=models.CharField(blank=True, max_length=300, verbose_name='游戏配置文件'),
        ),
    ]
